name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    # Build Vite project
    - name: Install dependencies and build
      run: |
        npm install
        npm run build  # Vite will output files to "dist/"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/ # Vite's default build output folder

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
