name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v3

    # Add this if your project needs a build step
    - name: Install dependencies and build
      run: |
        npm install
        npm run build  # Change this based on your project (e.g., npm run export for Next.js)

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/ # Change this to the correct output folder (e.g., 'out/' for Next.js)

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
